# ============================================================
#  fin — Selachii Package Manager
#  Selachii Project © 2026 — GPL v3
#  installer/hooks.py — Post-install package hooks & translation
# ============================================================
#
#  Reads `.INSTALL` scriptlets. Automatically translates Arch
#  `systemctl` commands into `SysVinit` equivalents.
#  Runs global ldconfig, cache updates securely.
# ============================================================

import os
import subprocess
from pathlib import Path

from ..config import get_config
from ..exceptions import HookError, HookTranslationError
from ..security.hook_scanner import scan_file, prompt_hook_approval

# Standard Arch auto-hooks that we manually execute
AUTO_HOOKS = [
    ["ldconfig"],
]

def run_auto_hooks(install_root: str = None):
    """Run standard desktop/system cache updates after a transaction."""
    root = install_root or get_config().install_root
    
    print("\n   [Hooks] Running global system updates...")
    for cmd in AUTO_HOOKS:
        # Check if binary exists in root
        bin_path = Path(root) / cmd[0].lstrip("/")
        # Some are just in PATH, let's use shutil.which or try-except
        
        try:
            # We don't fail the install if a hook binary is entirely missing 
            # (e.g. headless server doesn't have gtk-update-icon-cache)
            subprocess.run(
                cmd,
                cwd=root if root != "/" else None,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.STDOUT,
                timeout=60
            )

        except subprocess.TimeoutExpired:
            print(f"      - Warning: '{cmd[0]}' took too long and was skipped.")
        except (FileNotFoundError, OSError):
            continue


class HookRunner:
    def __init__(self, pkg_name: str, install_file: str, is_aur: bool = False):
        self.pkg_name = pkg_name
        self.install_file = install_file
        self.is_aur = is_aur
        self.config = get_config()
        self._in_chroot = self._detect_chroot()

    def _detect_chroot(self) -> bool:
        if not Path("/run/systemd/private").exists():
            try:
                root_stat = os.stat("/")
                pid1_root_stat = os.stat("/proc/1/root/.")
                return (root_stat.st_dev, root_stat.st_ino) != (pid1_root_stat.st_dev, pid1_root_stat.st_ino)
            except OSError:
                return True
        return False

    def run_phase(self, phase: str, version: str, old_version: str = ""):
        """
        Execute a specific phase function in the .install script.
        E.g. post_install, pre_upgrade.

        If the environment uses SysVinit, we intercept systemctl.
        """
        path = Path(self.install_file)
        if not path.exists():
            return

        # Phase 8: Hook Scanning implementation
        scan_result = scan_file(str(path))
        if not scan_result.safe:
            if self.is_aur:
                action = prompt_hook_approval(self.pkg_name, scan_result)
                if action == "A":
                    raise HookError(f"Install aborted by user due to security warnings in {self.pkg_name}.")
                elif action == "S":
                    print(f"   [Hooks] Skipping {phase} for {self.pkg_name} due to security concerns.")
                    return
                # action "R" continues execution
            else:
                # Auto-approve official
                pass

        # Read the script to find systemctl commands
        script_content = path.read_text(errors="replace")
        translated_content = self._translate_systemctl(script_content)

        # We write a temporary runner script to handle the bash sourcing
        runner_script = path.with_name(f".{self.pkg_name}_{phase}.sh")
        
        systemctl_wrapper = ""
        if self.config.init_system == "systemd" and self._in_chroot:
            systemctl_wrapper = """systemctl() {
    action="$1"
    service="$2"
    service="${service%.service}"
    case "$action" in
        enable)
            mkdir -p /etc/systemd/system/multi-user.target.wants
            ln -sf "/usr/lib/systemd/system/${service}.service" "/etc/systemd/system/multi-user.target.wants/${service}.service"
            ;;
        start|stop|restart|status|disable|daemon-reload)
            :
            ;;
        *)
            :
            ;;
    esac
}
"""

        bash_wrapper = f"""#!/bin/bash
# Hook wrapper generated by fin
{systemctl_wrapper}
{translated_content}

if type {phase} >/dev/null 2>&1; then
    {phase} {version} {old_version}
fi
"""
        runner_script.write_text(bash_wrapper)
        runner_script.chmod(0o755)

        print(f"   [Hooks] Running {phase} for {self.pkg_name}...")
        
        try:
            # Drop capabilities for AUR hooks if running as root
            env = os.environ.copy()
            cmd = [str(runner_script)]
            
            # (For safety on actual LFS, we'd use `sudo -u nobody` here if is_aur
            # but usually package install hooks NEED root to write to /etc/ or /var/lib.
            # fin's hook_scanner stops malicious rm -rf / before we get here).

            result = subprocess.run(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                env=env,
                timeout=120
            )

            # Log hook output safely
            if result.stdout.strip():
                self._log_hook_output(phase, result.stdout)

            if result.returncode != 0:
                print(f"   ⚠ Hook {phase} returned non-zero status ({result.returncode})")

        except subprocess.TimeoutExpired:
            print(f"   ⚠ Hook {phase} timed out after 120s")
        finally:
            if runner_script.exists():
                runner_script.unlink()

    def _translate_systemctl(self, script: str) -> str:
        """
        Translates Arch Linux `systemctl` native commands to SysVinit / OpenRC 
        depending on Selachii config.
        """
        init_sys = self.config.init_system
        if init_sys == "systemd":
            return script # no translation needed

        lines = script.splitlines()
        translated = []

        for line in lines:
            stripped = line.strip()
            if stripped.startswith("systemctl") or " systemctl " in stripped:
                translated.append(self._convert_systemd_line(stripped, init_sys))
            else:
                translated.append(line)

        return "\n".join(translated)

    def _convert_systemd_line(self, line: str, init_sys: str) -> str:
        """Convert a single line containing `systemctl`."""
        parts = line.split()
        if "systemctl" not in parts:
            return line

        idx = parts.index("systemctl")
        if idx + 2 >= len(parts):
            # Probably daemon-reload or status
            if "daemon-reload" in parts:
                return line.replace("systemctl daemon-reload", ":") # Do nothing mapped to true/colon
            return line
            
        action = parts[idx + 1]
        service = parts[idx + 2]
        
        # Strip .service
        if service.endswith(".service"):
            service = service[:-8]

        # sysvinit translation
        if init_sys == "sysvinit":
            if action == "enable":
                # Assuming update-rc.d or rc-update
                res = f"rc-update add {service} default"
            elif action == "disable":
                res = f"rc-update del {service}"
            elif action in ("start", "stop", "restart", "status"):
                res = f"/etc/init.d/{service} {action}"
            else:
                # Unsupported action
                res = ":"
        else:
            # fallback
            res = ":"

        # reconstruct
        new_parts = parts[:idx] + [res] + parts[idx+3:]
        return " ".join(new_parts)

    def _log_hook_output(self, phase: str, output: str):
        """Append to the rooted hooks.log"""
        from ..constants import LOG_HOOKS
        log_path = Path(LOG_HOOKS)
        
        try:
            log_path.parent.mkdir(parents=True, exist_ok=True)
            with log_path.open("a") as f:
                f.write(f"\n--- {self.pkg_name} ({phase}) ---\n")
                f.write(output)
                f.write("\n")
        except OSError:
            pass
