#!/bin/bash
# ============================================================
#  fin — Release Automator
#  Selachii Project © 2026 — GPL v3
#  scripts/release.sh — Atomic release workflow
# ============================================================

set -e

# ── Colors ───────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${CYAN}[fin]${NC} $1"; }
ok()    { echo -e "${GREEN}[  ✓ ]${NC} $1"; }
warn()  { echo -e "${YELLOW}[ !! ]${NC} $1"; }
fail()  { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

# ── Step 1: Detect Version ───────────────────────────────────
VERSION=$(grep 'VERSION       =' fin/constants.py | cut -d'"' -f2)
TAG="v$VERSION"

info "Preparing release for $TAG..."

# Check if tag already exists on GitHub
if gh release view "$TAG" &>/dev/null; then
    fail "Release $TAG already exists on GitHub! Update fin/constants.py for a new release."
fi

# ── Step 2: Build the Binary ─────────────────────────────────
info "Building standalone binary via PyInstaller..."
make build
if [ ! -f "dist/fin" ]; then
    fail "Build failed. Binary not found in dist/fin"
fi
ok "Binary build successful."

# ── Step 3: Git Tag & Push ───────────────────────────────────
info "Tagging local commit and pushing to origin..."
git tag "$TAG" || warn "Tag $TAG already exists locally. Continuing..."
git push origin "$TAG"
ok "Tag pushed to GitHub."

# ── Step 4: Create GitHub Release & Upload Asset ─────────────
info "Creating GitHub Release and uploading asset..."
cp dist/fin dist/fin-linux-x86_64
gh release create "$TAG" "dist/fin-linux-x86_64" \
    --title "fin $TAG" \
    --notes "Release generated by automated pipeline.
This release contains the statically compiled binary for x86_64 Linux systems (Selachii/LFS)."

ok "GitHub Release $TAG is now LIVE! 🦁🏁🚀"
echo ""
info "Your users can now upgrade using: sudo fin self-update"
echo ""
